apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-enfa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-enfa
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-enfa
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-enfa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-enfa
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ecwt-tenant/rhtap-demo-app/hacbs-test-project-enfa@sha256:f55b6c5141b1993e0f882c68ca81f2be76c0af3f62e8bde831498fd560caea4b
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
