apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-enfa
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ecwt-tenant/rhtap-demo-app/hacbs-test-project-enfa@sha256:f55b6c5141b1993e0f882c68ca81f2be76c0af3f62e8bde831498fd560caea4b
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
